/**
 * @file RRTOS_common.cpp
 * @brief RRTOS通用功能实现
 * @author Generated by AI Assistant
 * @date 2025-05-15
 * @details 实现RRTOS系统的全局变量和初始化函数
 */

#include "RRTOS_common.h"

namespace RRTOS {

// 在精简版中，不需要计数器

// 定义全局映射表
TopicQueueMap g_topicQueues;
ServiceSemaphoreMap g_serviceSemaphores;

// 定义全局互斥锁
SemaphoreHandle_t g_topicQueuesMutex = nullptr;
SemaphoreHandle_t g_serviceSemaphoresMutex = nullptr;



} // namespace RRTOS
